### ISSUE TITLE
Does not compile on standard mac

### ISSUE THREAD

**Issue by sigdestad** [enonic/starter-explorer-client#2]
~/searchtest$ ./gradlew deploy
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :webpack FAILED
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/tsi/searchtest/node_modules/webpack-cli/bin/cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webpack'.
> Process 'command '/Users/tsi/searchtest/.gradle/nodejs/node-v10.16.0-darwin-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
2 actionable tasks: 2 executed
~/searchtest$

**Comment by ComLock** [comment]
https://github.com/enonic/starter-explorer-client/commit/cc30ff78863bc7f5e3d48127886ed2c80b2cd3f2#diff-c197962302397baf3a4cc36463dce5eaL112
